#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================

ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep=config.ini

#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="WriteFreely daemon" --log="/var/log/$app/$app.log"

#=================================================
# MAKE THE UPGRADE
#=================================================

ynh_script_progression "Making the upgrade..."

pushd $install_dir
	ynh_mysql_db_shell <<< "ALTER DATABASE $db_name CHARACTER SET latin1 COLLATE latin1_swedish_ci;"

	ynh_exec_as_app ./writefreely db migrate
	ynh_exec_as_app ./writefreely --migrate
	ynh_exec_as_app ./writefreely keys generate
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Serving on"

#=================================================
# SET ADMINURL VARIABLE
#=================================================

if ynh_app_upgrading_from_version_before 0.16.0~ynh2
then
    ynh_script_progression "Setting admin url location..."

    if [ $path = "/" ]
    then
        ynh_app_setting_set --key=adminurl --value=https://$domain/admin/settings
    else
        ynh_app_setting_set --key=adminurl --value=https://$domain$path/admin/settings
    fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
